clang-tidy: remove unused private field
Drop unused private member bus from host-interface.hpp to resolve
-Wunused-private-field warning. No functional change.

Fixed below error
'''
../host-interface.hpp:46:23: error: private field 'bus' is not used [-Werror,-Wunused-private-field]
   46 |     sdbusplus::bus_t& bus;
'''

Change-Id: I18c82f512f51f1a640ef03a0a4e616753886a2b6
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>